# Generated by Django 2.1.4 on 2018-12-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('tombamento', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('sistema_oper', models.CharField(max_length=50)),
                ('licenca_so', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=50)),
                ('data_ultima_manutencao', models.DateField(blank=True)),
                ('data_proxima_manutencao', models.DateField(blank=True)),
                ('descricao_manutencao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('locada', models.BooleanField()),
                ('empresa_locadora', models.CharField(max_length=100)),
                ('data_ultima_manutencao', models.DateField()),
                ('data_proxima_manutencao', models.DateField()),
                ('descricao_manutencao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roteador_Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('tombamento', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=50)),
                ('senha_admin', models.CharField(max_length=50)),
                ('data_ultima_manutencao', models.DateField()),
                ('data_proxima_manutencao', models.DateField()),
                ('descricao_manutencao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('senha_admin', models.CharField(max_length=50)),
                ('data_ultima_manutencao', models.DateField()),
                ('data_proxima_manutencao', models.DateField()),
                ('descricao_manutencao', models.TextField()),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives_IT.Setor')),
            ],
        ),
        migrations.AddField(
            model_name='roteador_wifi',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives_IT.Setor'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives_IT.Setor'),
        ),
        migrations.AddField(
            model_name='computadores',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives_IT.Setor'),
        ),
    ]
