# Generated by Django 2.1.4 on 2018-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadores',
            name='dh',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computadores',
            name='memoria',
            field=models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB')], default='4GB', max_length=4),
        ),
        migrations.AddField(
            model_name='computadores',
            name='processador',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
