# Generated by Django 2.1.4 on 2018-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0002_auto_20181212_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadores',
            name='dh',
            field=models.CharField(choices=[('240GB', '240GB'), ('250GB', '250GB'), ('500GB', '500GB'), ('1000GB', '1000GB'), ('2000GB', '2000GB')], max_length=10),
        ),
    ]
