# Generated by Django 2.1.4 on 2018-12-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0003_auto_20181212_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computadores',
            old_name='dh',
            new_name='hd',
        ),
    ]
