# Generated by Django 2.1.4 on 2018-12-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0004_auto_20181212_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos_PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='computadores',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives_IT.Modelos_PC'),
        ),
    ]
