# Generated by Django 2.1.4 on 2018-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0005_auto_20181214_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadores',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
