# Generated by Django 2.1.4 on 2018-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0006_computadores_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteador_wifi',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
