# Generated by Django 2.1.4 on 2018-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0007_auto_20181214_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteador_wifi',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7),
        ),
    ]
