# Generated by Django 2.1.4 on 2018-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives_IT', '0010_auto_20181218_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutenção', 'Manutenção')], default='Ativo', max_length=7),
        ),
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutenção', 'Manutenção')], default='Ativo', max_length=7),
        ),
    ]
